global:
  scrape_interval: 4s
  scrape_timeout: 4s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "gean_node"
    static_configs:
      - targets:
        - host.docker.internal:8080
        labels:
          instance: local_node